#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use DrupalFinder\DrupalFinderComposerRuntime;

$finder = new DrupalFinderComposerRuntime();

echo json_encode([
    'getComposerRoot' => $finder->getComposerRoot(),
    'getVendorDir' => $finder->getVendorDir(),
    'getDrupalRoot' => $finder->getDrupalRoot(),
]);
